repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args:
    - --maxkb=2048
  - id: mixed-line-ending
    args:
    - --fix=auto

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.22.0
  hooks:
  - id: check-azure-pipelines

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.8


- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]

- repo: https://github.com/PyCQA/docformatter
  rev: v1.6.0
  hooks:
    - id: docformatter
      args:
      - "--in-place"
      - "--recursive"
      - "--wrap-summaries=90"
      - "--wrap-descriptions=84"
      - "--close-quotes-on-newline"

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ["--ignore=E501"]   # some lines were problematic, and pylint will eventually cover them

# - repo: https://github.com/pycqa/pylint
#   rev: v2.11.1
#   hooks:
#   - id: pylint

- repo: local
  hooks:
  - id: pytest
    name: pytest
    language: system
    entry: poetry run pytest
    pass_filenames: false
    stages:
    - push