version: "3.4"

networks:
  net:
    driver: overlay
    attachable: true

services:
  inventaire:
    build: .
    ports:
      - 8891:5000
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
    networks:
      - net